name: deploy
on:
  push:
    branches: ['main']
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install bazelisk
        uses: bazel-contrib/setup-bazel@0.9.0
        with:
          # Caches Bazelisk downloads based on .bazelversion
          bazelisk-cache: true
          # Caches Bazel external repositories and build outputs
          repository-cache: true
      - name: configure
        uses: actions/configure-pages@v5
      - name: build
        run: bazelisk build //docs
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{github.workspace}}/bazel-bin/docs/docs/_build/html
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
